# Generated by Django 3.1.1 on 2020-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('picture', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
